// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbCEbeulUnzPRvTiyEhB_xN3QzF5kidl0',
    appId: '1:807295592944:web:5f7e37881935542f0e5535',
    messagingSenderId: '807295592944',
    projectId: 'my-own-delivery-app',
    authDomain: 'my-own-delivery-app.firebaseapp.com',
    storageBucket: 'my-own-delivery-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsh9dJFXVFjzEUhQw7ErE2rdmWHgAwHYE',
    appId: '1:807295592944:android:bf81485757d737630e5535',
    messagingSenderId: '807295592944',
    projectId: 'my-own-delivery-app',
    storageBucket: 'my-own-delivery-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfqPhoKPFKG-Y8geWfHz_6zTdh3dLAbHI',
    appId: '1:807295592944:ios:930df460bb47a4860e5535',
    messagingSenderId: '807295592944',
    projectId: 'my-own-delivery-app',
    storageBucket: 'my-own-delivery-app.appspot.com',
    iosBundleId: 'com.example.foodDeliveryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfqPhoKPFKG-Y8geWfHz_6zTdh3dLAbHI',
    appId: '1:807295592944:ios:eef4e604ec1c78ae0e5535',
    messagingSenderId: '807295592944',
    projectId: 'my-own-delivery-app',
    storageBucket: 'my-own-delivery-app.appspot.com',
    iosBundleId: 'com.example.foodDeliveryApp.RunnerTests',
  );
}
